### ISSUE TITLE
Aerodynamic Calculation seems incorrect. 

### ISSUE THREAD

**Issue by HelixFDB** [cmd430/Warframe-EHP-Calculator#20]
As far as I know, Aerodynamic by itself is only 24%, yet when I apply it to any of my builds I'm getting what I can only assume as roughly ~66% DR (higher than the 50% DR gotten from the full Proton Set, yet far lower than the 90% DR gotten from Adaptation) resulting in a Base Excalibur with no other mods going from 825 EHP to 2063 EHP. It doesn't seem like the other Aura mods work on a function of having a full team, as Growing Power is only giving 25% power strength, and Stand United is giving the proper 25.5% armor multiplier.

**Comment by cmd430** [comment]
Thanks I’ll look into this after work tomorrow

**Comment by GlitchMC** [comment]
Aerodynamic seems to be providing 10% DR per rank:

Excal: 825
Rank1: 917
Rank2: 1032
......


I also agree with what i think Helix is saying, that it'd be nice to have either a box to say "There are four Stand United in our squad" (Coaction Drift would be a plus too), or have four separate aura boxes to be able to pick four different auras (and have each of those have their own C.D. checkbox).


By the way, I'm not sure if you know, and I also don't think you'd want to try to implement it since it'd be a pain,
But the way the Airborne mods work is subtracting directly from the health modifier for damage types. So vs Impact damage, health is normally 0.75x, but with Aerodynamic it'd be 51%, meaning it's more impactful on Impact and Gas, and less effective on Viral and Toxin, since those are 1.5x base.

Adaptation has its own mechanic too, but that's outside of the scope of the vacuum of the warframe, and has more to do with the enemies themselves.

**Comment by cmd430** [comment]
@GlitchMC coaction drift is already in the calculator under miscellaneous ;) 
as for the Airborne mods that's a touch out of what i feel like implementing as it would make the calculations more complicated (bearing in mind this tool is only to be used as a rough guide nothing more) like how with adaptation i just assume you have accumulated the 90% dr for each damage type you are receiving

for the auras i can probably add the multi select however i have the calculator setup so calculate for a solo player since thats more reliable - hence no squad abilities - so i probably wont add this, i might if i find enough time though we'll see in the future

**Comment by cmd430** [comment]
this is fixed by https://github.com/cmd430/Warframe-EHP-Calculator/commit/f1931cbf3eb30e661d1a661a44f2e1f3adbb1124 

(I had accidentally used the aim glide bonus value not the damage reduction value...)

**Comment by GlitchMC** [comment]
Oh, yeah, I know that CD is there, I was meaning being able to say that you have like, 3x Corrosive Projection, but only have 2x Coaction Drifts.
